name: Build with Maven

on:
  push:
    branches:
      - '2.x.x'
      - 'master'
  pull_request:
    branches:
      - '2.x.x'
      - 'master'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [8, 11, 17]

    env:
      JAVA_VERSION: ${{ matrix.java-version }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin
          cache: maven

      - name: Configure MAVEN_OPTS for Java 9+
        if: ${{ matrix.java-version != 8 }}
        run: |
          echo "MAVEN_OPTS=--add-opens java.xml/jdk.xml.internal=ALL-UNNAMED" >> $GITHUB_ENV
          echo "MAVEN_OPTS=$MAVEN_OPTS --add-opens java.base/java.lang=ALL-UNNAMED" >> $GITHUB_ENV
          echo "MAVEN_OPTS=$MAVEN_OPTS --add-opens java.base/java.io=ALL-UNNAMED" >> $GITHUB_ENV

      - name: Install dependencies
        run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --show-version --file pom.xml

      - name: Build and Test with Maven
        run: mvn test --batch-mode --show-version --file pom.xml
