name: Build with Maven

on:
  push:
    branches:
      - '2.x.x'
      - 'master'
  pull_request:
    branches:
      - '2.x.x'
      - 'master'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [8, 11, 17]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin
          cache: maven

      - name: Build and Test with Maven
        run: |
          if [[ "${{ matrix.java-version }}" == "8" ]]; then
            MAVEN_OPTS=""
          else
            MAVEN_OPTS="--add-opens java.xml/jdk.xml.internal=ALL-UNNAMED"
          fi
          mvn clean install --batch-mode --show-version --file pom.xml
